### ISSUE TITLE
[BUG] sqm-autorate stopped whenever interface or WAN router restarted

### ISSUE THREAD

**Issue by malikshi** [sqm-autorate/sqm-autorate#105]
**Script Version**
The version which exhibited this bug behavior. Can be found via `/usr/lib/sqm-autorate/sqm-autorate.lua -v` or in the first line of `/tmp/sqm-autorate.log`.
version: `Starting sqm-autorate.lua v0.4.3`
log from `/usr/lib/sqm-autorate/sqm-autorate.lua -v`
```sh
root@MalikWRT /tmp49# /usr/lib/sqm-autorate/sqm-autorate.lua -v
lua: module 'vstruct' not found:
        no field package.preload['vstruct']
        no file './vstruct.lua'
        no file '/usr/share/lua/vstruct.lua'
        no file '/usr/share/lua/vstruct/init.lua'
        no file '/usr/lib/lua/vstruct.lua'
        no file '/usr/lib/lua/vstruct/init.lua'
        no file './vstruct.so'
        no file '/usr/lib/lua/vstruct.so'
        no file '/usr/lib/lua/loadall.so'
stack traceback:
        [C]: ?
        [C]: in function 'require'
        /usr/lib/sqm-autorate/sqm-autorate.lua:59: in main chunk
        [C]: ?
```
log from `/tmp/sqm-autorate.log`
```sh
root@MalikWRT /tmp49# cat sqm-autorate.log
Starting sqm-autorate.lua v0.4.3
Something went wrong in the regulator thread
/usr/lib/sqm-autorate/sqm-autorate.lua:833: bad argument #2 to 'format' (string expected, got nil)
```
**Describe the bug**
I think this one similar to #101 
**To Reproduce**
My router 4g rebooted since having problem no signal/dropping signal to 3G which is basically no internet access.
**OpenWrt Details (please paste your output from `cat /etc/os-release`):**
 - OS-Release: `21.02.1`
 - Connection Type + Speed: B818 LAN-USB EU300 with cable cat 7 to Openwrt RPI4B

**Comment by malikshi** [comment]
> can you take a look at #99 and confirm whether this looks like the same issue?

I never used `log_level=DEBUG` so I will try those setting later and I can test your adjustment too.

**Comment by jeverley** [comment]
Good call out, it will actually affect all log levels since the nested string.format function is executed before calling the logger function. The fix should work regardless of log level 🙂 I'll correct that assessment in the original issue.

**Comment by malikshi** [comment]
> it will actually affect all log levels

the service seem having problem for all type of log level. Mine crashed after few hour running at log_level INFO here
[openwrtstats.txt](https://github.com/Fail-Safe/sqm-autorate/files/7866337/openwrtstats.txt)

**Comment by jeverley** [comment]
Hi @malikshi, that's good news on the first issue.
You're now seeing the issue I reported in https://github.com/sqm-autorate/sqm-autorate/issues/101.
There's a proposed fix for this too.

**Comment by malikshi** [comment]
@jeverley 
> that's good news on the first issue. You're now seeing the issue I reported in #101. There's a proposed fix for this too.

```
[WARN - 20220114T19:27:27]: One or both stats files could not be read. Skipping rate control algorithm.
[INFO - 20220114T19:27:27]: reflector: 94.140.15.15 delay: 3.8298651041093  down_del: 5.2139929447519
[INFO - 20220114T19:27:27]: reflector: 103.153.154.2 delay: 2.6496258454373  down_del: 0.16377100636177
[INFO - 20220114T19:27:27]: reflector: 119.235.48.3 delay: 9.1590907920953  down_del: 0.5742716959241
[INFO - 20220114T19:27:27]: reflector: 103.146.221.20 delay: 7.5137058565154  down_del: 0.69677288005068
```
i tried your patch #112 indeed it's keep services stay alive. and of course thread still UP too.
checking time to time the `tc qdisc` no any changes so the rate control stopped.
```
qdisc noqueue 0: dev lo root refcnt 2
qdisc mq 0: dev eth0 root
qdisc fq_codel 0: dev eth0 parent :5 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc fq_codel 0: dev eth0 parent :4 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc fq_codel 0: dev eth0 parent :3 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc fq_codel 0: dev eth0 parent :2 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc fq_codel 0: dev eth0 parent :1 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc cake 8020: dev eth1 root refcnt 2 bandwidth 13176Kbit besteffort dual-srchost nat nowash ack-filter split-gso rtt 50ms noatm overhead 44 mpu 68
qdisc ingress ffff: dev eth1 parent ffff:fff1 ----------------
qdisc fq_codel 0: dev wlan1 root refcnt 2 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc noqueue 0: dev br-lan root refcnt 2
qdisc mq 0: dev wwan root
qdisc fq_codel 0: dev wwan parent :4 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc fq_codel 0: dev wwan parent :3 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc fq_codel 0: dev wwan parent :2 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc fq_codel 0: dev wwan parent :1 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms memory_limit 4Mb ecn drop_batch 64
qdisc cake 8021: dev ifb4eth1 root refcnt 2 bandwidth 24712Kbit besteffort dual-dsthost nat wash ingress no-ack-filter split-gso rtt 50ms noatm overhead 44 mpu 68
```

**Comment by jeverley** [comment]
Thanks for the feedback @malikshi, I can replicate this my end too will look at the trances and make additional fixes in PR 112 then.

**Comment by jeverley** [comment]
HI @malikshi would you like to try the updated changes in #112 ? It's now handling this scenario correctly on my system.

In summary, once the device is re-connected the old file descriptors for the rx/tx stats files are no longer valid.
The ratecontrol function will now attempt to re-open these in the event that the bytes values cannot be read, it will also ensure the previous bytes and reading time values are handled appropriately in this scenario.

**Comment by malikshi** [comment]
> In summary, once the device is re-connected the old file descriptors for the rx/tx stats files are no longer valid.
> The ratecontrol function will now attempt to re-open these in the event that the bytes values cannot be read, it will also ensure the previous bytes and reading time values are handled appropriately in this scenario.

@jeverley, I tested by restarting the interface and yes it works as you mentioned above.

**Comment by Fail-Safe** [comment]
Adding this confirming this is existing in v0.4.4 as well:

```shell
root@OpenWrt:~# cat /tmp/sqm-autorate.log
Starting sqm-autorate.lua v0.4.4
[WARN - 20220124T13:36:13]: One or both stats files could not be read. Skipping rate control algorithm.
Something went wrong in the regulator thread
/usr/lib/sqm-autorate/sqm-autorate.lua:817: attempt to concatenate local 'next_dl_rate' (a nil value)
```
