### ISSUE TITLE
[BUG] 0.4.4 stops running (crashes?) overnight

### ISSUE THREAD

**Issue by richb-hanover** [sqm-autorate/sqm-autorate#120]
**Script Version** 0.4.4

**Describe the bug**
I start sqm-autorate as normal, it works fine, but when I check in the morning, it's not running. I don't see `sqm-autorate.lua` in `top`, `tc -s qdisc` is static, and no data are being written to `/tmp/sqm-autorate.csv`

**To Reproduce**
1. Use remove.sh and setup.sh scripts from `lua-threads` branch
2. Set upload and download nominal values; accept default of 20%
3. Let it run. _sqm-autorate_ adapts to traffic as expected.
4. Go away, come back in the morning
5. Not working, as shown by the symptoms above

**Expected behavior**
_sqm-autorate_ should run for an arbitrarily long time period

**Hypothesis:** The file system is filling up. Here's `df -h`

```
root@D-Link-DIR-878:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.8M      4.8M         0 100% /rom
tmpfs                    59.7M     49.4M     10.3M  83% /tmp
/dev/mtdblock6            8.8M      7.8M    984.0K  89% /overlay
overlayfs:/overlay        8.8M      7.8M    984.0K  89% /
tmpfs                   512.0K         0    512.0K   0% /dev
```

**OpenWrt Details (please paste your output from `cat /etc/os-release`):**
 - OS-Release: 21.02.1
 - Connection Type + Speed: 25/25 symmetric

**Additional context**
SQM Debug files: [openwrtstats-2022-01-18-080429.gz](https://github.com/sqm-autorate/sqm-autorate/files/7889325/openwrtstats-2022-01-18-080429.gz)

**Comment by chas-iot** [comment]
possible duplicate of #48 ?

**Comment by richb-hanover** [comment]
> possible duplicate of #48 ?

This is likely to be exactly the same problem. This report contains a bunch of debugging info if that became helpful. Thanks.

PS And how would I turn off all the logging to avoid this problem?

**Comment by chas-iot** [comment]
In `/etc/config/sqm-autorate`, change `log_level` to WARN, ERROR, or FATAL.

This will largely mitigate but not prevent the issue because /tmp/sqm-autorate.csv can also grow unbounded, but at 1/10 the rate of /tmp/sqm-autorate.log

**Comment by richb-hanover** [comment]
Actually, the log_level only affects the sqm-autorate.log file (via the logger() function). Both the sqm-autorate.csv and sqm-speedhist.csv files are written through their own fd:write() calls.

**Comment by richb-hanover** [comment]
The problem seems to have been running out of space on the `/tmp` file system. It ran overnight with my local change.

I updated my copy of _sqm-autorate.lua_ to include a new `csv_logger()` function that handles the CSV files AND observes `use_loglevel.level.` Here's the code (inserted above `logger()` function).

```
-- homegrown logger for CSV files to keep us from having to import yet another module
local function csv_logger(fd, loglevel, message)
    if (loglevel.level <= use_loglevel.level) then
        -- local cur_date = os.date("%Y%m%dT%H:%M:%S")
        -- local cur_date = os.date("%c")
        -- local out_str = string.format("[%s - %s]: %s", loglevel.name, cur_date, message)
        fd:write(message)
    end
end
```
and I modified the (four) calls to `xxx_fd:write()` in the obvious way, i.e.,

```
696,697c717,721
<     csv_fd:write("times,timens,rxload,txload,deltadelaydown,deltadelayup,dlrate,uprate\n")
<     speeddump_fd:write("time,counter,upspeed,downspeed\n")
---
>     csv_logger(csv_fd, loglevel.INFO,"times,timens,rxload,txload,deltadelaydown,deltadelayup,dlrate,uprate\n")
>     csv_logger(speeddump_fd, loglevel.INFO,"time,counter,upspeed,downspeed\n")
```

(The fix needs to be made in two other places where the actual logging message is written.)

Obviously, this should be merged into the `logger()` function, but I wasn't sure how to specify a file descriptor for whatever file gets written with `print()` So to test the situation, I just created a separate function.

**Comment by richb-hanover** [comment]
I committed version 0.4.5 that introduces a `csv_logger()` function that honors the `log_level`. That addresses my concerns. https://github.com/sqm-autorate/sqm-autorate/commit/a566f02a15f6441353359c01d2f81a4243bb7f1a
