### ISSUE TITLE
[FEATURE] Reconsider decision (not) to use /etc/config/sqm as a base

### ISSUE THREAD

**Issue by richb-hanover** [sqm-autorate/sqm-autorate#127]
I am somewhat frustrated that (a while back) we decided not to use `/etc/config/sqm` as a base for the `sqm-autorate` settings. I would like to bring this up again, because doing this would be a real boon to adoption.

After installing and configuring SQM (via, say `luci-app-sqm`), there are good and useful values in its config file: both the proper interface, and the base settings. 

It's easy for a newcomer to set up SQM, then run the `setup.sh` script. If that script could snag the base values from the SQM config, they wouldn't have to do any editing.

And this would be a strong step toward a simple package (or an enhancement to the `luci-app-sqm` package) that "just works" for varying speed links.

**Describe the solution you'd like**
retrieve up & down speeds, and interface names from `/etc/config/sqm`

**Describe alternatives you've considered**
There was a previous discussion (on the forum?) about the difficulties in doing this. Perhaps these decisions could be re-considered for longer-term. Thanks.

**Comment by chas-iot** [comment]
If this is desired then it **must** consider configurations with multiple independent sqm setups. Not impossible, also not straightforward.

**Comment by richb-hanover** [comment]
Ah yes, multiple configurations... That was the blocker. At least this consideration is now called out in a separate issue, instead of buried in a Forum thread. Thanks.

**Comment by richb-hanover** [comment]
Having taken a few days off from sqm-autorate, I realize that the installer could check the `/etc/config/sqm` and if there's only one interface, it could use the values.

If there are multiple sqm setups, then the installer could bail, with a warning to edit `/etc/config/sqm-autorate`... Thanks again.

**Comment by richb-hanover** [comment]
The `develop/setup-config` is designed to address this. Closing this, will reopen new issues as needed.
