### ISSUE TITLE
[BUG] develop/main - crash due to unset SQMA_NO_STATISTICS environment variable

### ISSUE THREAD

**Issue by jeverley** [sqm-autorate/sqm-autorate#131]
**Script Version**
v0.4.4 - develop/main post merge of #123 

**Describe the bug**

The service crashes when the no_statistics paremeter is not specified (either by config, cli arg or environment variable).

```
lua: ./sqma-settings.lua:356: bad argument #1 to 'lower' (string expected, got nil)
stack traceback:
	[C]: in function 'lower'
	./sqma-settings.lua:356: in function 'initialise'
	sqm-autorate.lua:115: in main chunk
	[C]: ?
```

This is because of the following section of code:

```
if not suppress_statistics then
    suppress_statistics = os.getenv("SQMA_NO_STATISTICS")
    suppress_statistics = suppress_statistics == "1" or
        string.lower(suppress_statistics) == "true" or
        string.lower(suppress_statistics) == "true" or
        string.lower(suppress_statistics) == "yes" or
        string.lower(suppress_statistics) == "y"
end
```

The string.lower() function cannot be passed a nil input (which occurs when the environment variable is not set).
This can be protected against by wrapping the os.getenv() function within tostring() as below:

```
suppress_statistics = tostring(os.getenv("SQMA_NO_STATISTICS"))
```

@chas-iot  should be a straightforward one to fix 🙂

**Comment by chas-iot** [comment]
oops, that clearly escaped my testing

**Comment by chas-iot** [comment]
After checking, I was clearly working while too tired. There were several dumb issues in that section of code that were changed after being first tested then merged direct to develop/main.
Apologies
