### ISSUE TITLE
[BUG] Version 0.5.0-RC1 doesn't give good speeds

### ISSUE THREAD

**Issue by richb-hanover** [sqm-autorate/sqm-autorate#138]
**Script Version** 0.5.0-release candidate 1 from this morning

**Describe the bug**
Download speed doesn't get very high, and then gets yanked back down to minimum on a regular basis. Upload speed doesn't seem to be affected as much

**To Reproduce**
1. Run the `...remove.sh` from the `testing/lua-threads` That seemed to work as expected.
2. Run the `...setup.sh` script as shown in output below
3. Enable and start the service
4. Problem 1: The download speed gets only to about half the configured download speed
4. Problem 2: `tail -f /tmp/sqm-autorate.csv` shows many jumps back to the 20%/50% level, like this...
```
1643814911,409823197,0.062060,0.991684,8.243961,5.504787,8992,26321
1643814911,976158733,0.066296,0.844847,7.966115,4.000531,8992,27168
1643814912,604469259,0.068578,1.012927,17.085392,3.174429,2000,27963
1643814913,183418844,0.419483,0.924305,19.179442,1.928671,2000,28706
```

**Expected behavior**
This is a regression from earlier versions (0.4.4) that would remain at the higher "download" setting until one of the periodic spikes. Also the download speed never gets to the configured speed. Upload speed does...

**OpenWrt Details (please paste your output from `cat /etc/os-release`):**
 - OS-Release: 21.02.1 
 - Connection Type + Speed:

**Additional context**
Set the attached debugging files:
[openwrtstats-2022-02-02-101824.gz](https://github.com/sqm-autorate/sqm-autorate/files/7987804/openwrtstats-2022-02-02-101824.gz)

```
root@D-Link-DIR-878:~# wget -q -O- https://raw.githubusercontent.com/sqm-autorat
e/sqm-autorate/testing/next/sqm-autorate-setup.sh > sqm-autorate-setup.sh
root@D-Link-DIR-878:~# ./sqm-autorate-setup.sh testing/next
-ash: ./sqm-autorate-setup.sh: Permission denied
root@D-Link-DIR-878:~# sh ./sqm-autorate-setup.sh testing/next
>>> Refreshing package cache. This may take several minutes...
>>> Installing required packages via opkg...
>>> Installing required packages via luarocks...
Installing https://luarocks.org/vstruct-2.1.1-1.src.rock...
Using https://luarocks.org/vstruct-2.1.1-1.src.rock... switching to 'build' mode
Updating manifest for /usr/lib/luarocks/rocks
vstruct 2.1.1-1 is now built and installed in /usr

>>> Pulling down sqm-autorate operational files...
>>> Putting sqm-autorate lib files into place...
>>> Making sqm-autorate.lua and getstats.sh executable...
>>> Putting config file into place...
>>> Putting service file into place...
> All done! You can enable and start the service by executing 'service sqm-autorate enable && service sqm-autorate start'.
root@D-Link-DIR-878:~# service sqm-autorate enable && service sqm-autorate start
```

**Comment by richb-hanover** [comment]
**Update:** The behavior was so unexpected that I did more checking...

1. It turns out there were two instances of `sqm-autorate.lua` running. (Check the `top` output) I killed both and restarted the service. Now only one is running. Things look better, but not perfect.
2. I still see the download speed setting dropped to 50% of the configured rate when there's not much happening. To be specific, when I `tail -f /tmp/sqm-autorate.csv`, I see:

- `... 13250,31531` # 13250 is 50% of the configured 26,500 kbps DL setting

- During a download portion of a speed test, the 13250 creeps up to ~34000 (which is normal from other versions, say 0.4.4)

- Shortly after the upload portion of the speed test begins the DL speed drops back to 13250 (exactly) and stays there

- When I download more data, the DL speed inches backup again, only to drop during periods of low/no download activity. This seems repeatable.

What other information could I provide? Thanks!

**Comment by richb-hanover** [comment]
**Update x2:** I left the service running longer (it's been about a half-hour now) and the download speed is acting right - it's going up to a max of 46163 (again, within bounds from the 0.4.4 version) and staying there longer-term.

So (nearly) everything is explained: 

- Is it reasonable to state that  the "rapid drop back to 50% speed" behavior only occurred during the "training interval"?

- Why did I have two instances of `sqm-autorate.lua` running? I checked the history of my terminal session, and I _did_ run the `...remove.sh` script, which indicated that it was disabling and stopping the sqm-autorate service.

**Comment by chas-iot** [comment]
Does it make sense to close this as not a bug?

**Comment by richb-hanover** [comment]
Yes - I'll open a new issue if I see something odd. Thanks.
