### ISSUE TITLE
[FEATURE] What improvements could be made to the setup and remove scripts?

### ISSUE THREAD

**Issue by chas-iot** [sqm-autorate/sqm-autorate#140]
Let's use this to gather requirements for future versions of the setup and remove scripts

1. Ensure that by default, _sqm-autorate_ does not fill the router storage and crash. More changes required elsewhere to support this, however the setup script will play a part.
2. see if we can pull some information from `/etc/config/sqm` - this is not done at the moment because there may be more than 1 CAKE setup. - #127 
3. Ask some targetted questions regarding speeds and connection technologies to create a better initial `/etc/config/sqm-autorate`

Please add further suggestions?

**Comment by jeverley** [comment]
@chas-iot  apologies for the misclick! - I've been putting some thought to this, and also how we ought to manage config for multi interface setups. I'd like to get your thoughts on the following considerations:

- Should configuration be based around OpenWrt interface or underlying device?
Touched on in #103
My thoughts/considerations here:
  - OpenWrt manages network configuration per interface, and the interaces are associated to a device (using static config, or dynamically upon ifup for tun/ppp/wwan type interfaces).
  This means that a device name associated with an interface could theoretically change when devices are torndown.
  _This interface concept may be quite OpenWrt specific however._
  - The SQM scripts on the other hand are configured at the device level, this is more platform agnostic, however can make managing configuration for more complex setups a bit convoluted (i.e. configuring the ingess on a veth/lan device's upload, and egress on the upload separatey on primary the wan inferface).
  _This setup is fairly common as it allows users to set the DSCP mark of downloaded packets before they reach the cake queue._
  - I'm wondering if a compromise might be to have the service configured at the interface/egress device level, and allow for specification of a manual download device (this would then tally up with the devices configured under SQM setup and we could pull these in during initial setup).

I've included a mockup reflecting my own setup (a PPPoE and QMI modem connection)

```
config interface 'wan'                             # PPPoE interface - OpenWrt creates a ppp device during ifup (pppoe-{interface name})
        option upload_interface 'pppoe-wan'        # if absent this could be derived from the interface's l3_device using UCI
        option download_interface 'ifb4pppoe-wan'  # if absent this could fall back to the ifb4 + upload_interface
        option upload_base_kbits '2500'
        option download_base_kbits '20000'
        option upload_min_percent '20'
        option download_min_percent '20'

config interface 'wwan'                            # QMI interface -  OpenWrt determines the network device during ifup from the associated control device (as these are commonly USB, the wwanX can change)
        option upload_interface 'wwan0'            # if absent this could be derived from the interface's l3_device using UCI
        option download_interface 'br-lan'         # if absent this could fall back to the ifb4 + upload_interface
        option upload_base_kbits '2500'
        option download_base_kbits '20000'
        option upload_min_percent '20'
        option download_min_percent '20'

config output
        option log_level 'WARN'
        option suppress_statistics 'no'
        option stats_file '/tmp/sqm-autorate.csv'
        option speed_hist_file '/tmp/sqm-speedhist.csv'
```

**Comment by chas-iot** [comment]
@jeverley I see helping the ‘mainstream’ single wan interface user get the basics set up as a higher priority - i.e. where I expect to put my efforts. I’m finishing up the rate controller plugin (this week, I hope) then I’ll start looking at the setup script again.

Regarding the multi-interface, I’m not sure that the core _sqm-autorate.lua_ script is currently able to support this requirement - wouldn’t it need to send the ICMP requests on a specific network or device?

**Comment by chas-iot** [comment]
> wouldn’t it need to send the ICMP requests on a specific network or device?

alternatively _sqm-autorate.lua_ should largely work with primary/fallback interfaces where the speeds and delays are not too different between the two interfaces.

**Comment by jeverley** [comment]
> @jeverley I see helping the ‘mainstream’ single wan interface user get the basics set up as a higher priority - i.e. where I expect to put my efforts. This is not a reason to block your proposals. I’m finishing up the rate controller plugin (this week, I hope) then I’ll start looking at the setup script again.

@chas-iot Definitely makes sense to prioritise this first 🙂 Just wanted to make sure this was on your radar when making implementation decisions.

> Regarding the multi-interface, I’m not sure that the core _sqm-autorate.lua_ script is currently able to support this requirement - wouldn’t it need to send the ICMP requests on a specific network or device?

I was able to address sending packets off the correct interface on my local branch based on 4.x code base prior to the modularisation merges, parked that whilst you were tidying things up ahead of v5 - I'll create a PR to merge the device pinning as without it the script starts pinging over the failover device (which threw off the primary stats).

> alternatively sqm-autorate.lua should largely work with primary/fallback interfaces where the speeds and delays are not too different between the two interfaces.

I'd recommend we keep the two data sets separate, in my case the LTE link is 10 x the speed of the fallback, but has double the base RTT.
I'll create a develop branch incorporating my ideas here and keep this up to date with your modularisation changes.
Will keep you in the loop!

**Comment by richb-hanover** [comment]
* `setup.sh` should stop, if not disable, any running `sqm-autorate` instances. (I was astonished to see two copies running 'til I figured out what happened...)

**Comment by chas-iot** [comment]
picking up #146
