### ISSUE TITLE
Where's the storage? (High CPU usage...)

### ISSUE THREAD

**Issue by richb-hanover** [sqm-autorate/sqm-autorate#147]
I installed @chas-iot's `t` branch (https://github.com/chas-iot/sqm-autorate/tree/t) that incorporates cpu-profiling and the setup-config on my Archer C7v2 running 21.02.1.

I notice an odd pattern of CPU use: After an initial install, the CPU usage hangs around 50%. If I generate a bunch of traffic (to start training the sqm-autorate process), the CPU utilization jumps to ~100%.

BUT... After the traffic stops (after the 30 second test) the CPU load stays high for a couple minutes on an otherwise idle router. I attach a link to a video of the `htop`. There's a narration of the events below.

**My question:** Where's the storage? What causes the CPU to stay high after the traffic stops? What feeds the sqm process? Why does it stop after a couple minutes (why not five seconds? or 10 minutes? or Never?) Thanks.

Video of `htop` during and after the traffic: https://youtu.be/F11N_r6pgwQ

22:45:15 - start recording the video with 22:45:15 on the Uptime counter...
	- Note CPU usage is about 50%, most of that is the lua process

22:45:21 - start the netperfrunner.sh script that sends bidirectional netperf traffic for 30 seconds.
	- Note htop CPU meter is pegged at 100%
	- lua process is running around 60%

22:45:51 netperfrunner.sh completes

22:45:53 a couple seconds afterwards...
	- Lua process jumps to 98% and remains there for about two minutes

22:47:45
	- Lua process then falls to 50% where it remains.

NB: This is likely related to https://github.com/sqm-autorate/sqm-autorate/issues/139, but provides more details about the dynamics...

**Comment by Lochnair** [comment]
- The receiver thread blocks on recvfrom until a packet is available on the socket
- The packet is parsed and sent to a Linda that acts as a queue
- The baseliner thread blocks on receiving from the queue and handle any additions as soon as it can

So yeah, in theory we could end up with multiple items on the queue if the baseliner function isn't processing them fast enough

**Comment by richb-hanover** [comment]
I'm feeling a fair amount of cognitive dissonance here... And I'm having a hard time believing that the _baseliner_ code actually requires that much CPU. 

On the one hand, "all it's doing" - the baseliner - is comparing a bunch of readings from each ping packet (a straight-through set of if/then/else's) and setting some values in the owd_tables. (At least to my newcomer eyes...)

And on the other hand, our processors are pretty powerful (even a 720 MHz single core processor of the Archer C7).

Some questions:

- Have we instrumented the processing time for the main loop within the baseliner thread? (For example, what if the stats_queue:receive() call always returned a pre-defined value. How many times per second could we go through this loop?)
- Do we know how many ping packets are being generated/processed (per second/per minute)?
- Is it conceivable that the inter-thread communication time could be significant? How many recvfrom() calls per second could we accomplish?

Thanks, as always.

**Comment by Lochnair** [comment]
> On the one hand, "all it's doing" - the baseliner - is comparing a bunch of readings from each ping packet (a straight-through set of if/then/else's) and setting some values in the owd_tables. (At least to my newcomer eyes...)
>
>This makes it hard to believe that the baseliner code actually requires that much CPU.

Yes, you are right, that really is all it does. I'm sure you understand my confusion when I saw how much CPU that thread used :P

> Have we instrumented the processing time for the main loop within the baseliner thread? (For example, what if the stats_queue:receive() call always returned a pre-defined value. How many times per second could we go through this loop?)

We haven't, although I'm not sure I see a way for that to happen. Since it's a producer/consumer paradigm, if there's nothing in the queue it'll just wait until there is.

> Do we know how many ping packets are being generated/processed (per second/per minute)?

Not accounting for peer selection, the tick rate is 0.5s, and we spread apart sending packets to each reflector by taking the tick rate divided by the amount of reflectors (5 normally) and sleeping between each send - so we send one packet every 0.1s.

If we consider the reselection, it takes 20 random reflectors and pings those for tick rate (0.5s) * PI, so basically 3 ticks worth.
That means in the span of 1.5s we send 60 packets, which is why you'll see heightened CPU usage while it's doing that.

We receive at mostly the same rate as we send (with the assumption that the reflectors have a similar RTT).
The receiver also gets any other ICMP packets passing through (since it's a raw socket it gets everything), but those are quickly dismissed and the loop continues.

> Is it conceivable that the inter-thread communication time could be significant? How many recvfrom() calls per second could we accomplish?

Looks like it. And not sure. I believe on of the reasons the ping threads also use a fair bit of CPU is that they're getting the reflector list every time the loops run, which seems to be painful CPU wise.

I'm not sure if it's the locking happening under the hood that hurts performance or if it's something else.

**Comment by richb-hanover** [comment]
Thanks for the detailed response. A couple further thoughts:

re: "instrumenting the loop" I was wondering about replacing stats_queue:receive() with a "stub function" (no interprocess call - IPC) that simply returns a (constant) data structure that looks like real data. That could determine how much time it takes for a pass through the baseliner loop. (Or how many passes through the loop per second when if it never has to wait for real data)

re: benchmarking inter-process calls. In a slightly different vein, perhaps there could be a replacement thread that always had a bogus (constant?) response ready to return. This could be a second step for the instrumentation above. The first step is a simple function that returns a value, the second does the IPC and returns a "canned" value.

re: Ping rate. I had forgotten that sqm-autorate sends 10 packets/second, or the duration the algorithm maintains that packet rate. This is useful for our experiments to control latency. But more globally, I worry about this behavior/packet rate if sqm-autorate should become popular. If 10 million devices start using the algorithm, that would be 100 million new packets per second of traffic - a not necessarily welcome outcome. Perhaps we can also begin to experiment with decreasing the packet rate to see where latency control begins to decrease. Not only would this decrease load on the global internet, but would decrease the amount of processing required for sqm-autorate.

Thanks again.

**Comment by richb-hanover** [comment]
To be clear about my "instrumenting" comment... Perhaps we should create a "develop-profiling" branch that exists only run these tests. I won't control latency, but could answer these questions;

- how many loops per second for _baseliner_ if stats_queue:receive() returns a data value in 0msec? 
- what's the max rate we can send pings (perhaps to localhost)?
- what's the max rate of receiving pings (perhaps receiving from the previous step)?
- would there be a way to see if ping packets were queueing up (in the kernel?) if the receive rate was below the sending rate?
- how could we measure other inter-thread call times?

Thanks.

**Comment by richb-hanover** [comment]
**Update:** CPU usage on my Archer C7v2 drops dramatically (down to ~20-30% continuous, with brief peaks of 60-70%) if I change `/usr/lib/sqm-autorate/sqma-settings.lua` to contain:

```
    M.tick_duration = 1.0 -- Frequency in seconds
    M.min_change_interval = 1.0 -- don't change speeds unless this many seconds has passed since last change
```
I suspect that decreases the "ping rate" as suggested above. I don't have a good setup for testing whether speed/latency is well regulated: I have 25mbps/25mbps fiber that gives good, constant speeds.

**Comment by richb-hanover** [comment]
I think this is too old to be interesting. I am closing it.
