### ISSUE TITLE
What's the difference to cake-autorotate?

### ISSUE THREAD

**Issue by pannal** [sqm-autorate/sqm-autorate#157]
Hey, sorry for the maybe stupid question, but this seems to do the exact same as https://github.com/lynxthecat/cake-autorate while being a lot more complex.

Are the projects basically the same, sqm-autorotate just offering more visualization features?

Thank you!

**Comment by Lochnair** [comment]
It's not stupid at all :)

The gist of it is that what become sqm-autorate, was originally meant to be a Lua port of cake-autorate,
but do to how Lua works, it proved difficult to do a proper port.

Due to this we ended up with a different approach, so while the projects has the same goal, they function differently.
Currently cake-autorate uses ICMP echo requests (normal ping) to determine latency, this means bufferbloat on uplink would also lower shaper rate on downlink (there are plans to change this though).

This implementation uses ICMP timestamps, which allows us to determine (to some degree of accuracy) one-way delay,
i.e. bufferbloat on uplink would only lower the shaper rates in that direction, but as you say this project is in some ways more complex, so there's trade-offs both ways.

There's also another approach written in Perl here (that also uses one-way delays): https://github.com/tievolu/sqm-autorate

I'd recommend you simply test them and see what works best for you, and do please report back your experience in the forum thread that covers all of these: https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/135379 :)

**Comment by pannal** [comment]
Oh I never expected such a thorough answer, thank you.

I've just recently moved from using my ASUS RT-AX86U for routing and Wi-Fi, towards a Topton N5105 box with OpenWRT that handles routing, and the ASUS just being an AP. The reason was: I've switched to a 1G down/50M up cable/docsis connection that the ASUS was not under any circumstances able to shape properly, not even with only fq_codel (Steam downloads racked up 15% packet loss in TS3 over the course of a minute).

So far I'm heavily impressed, knowing how OpenWRT looked like before the chaos calmer days. 

I'm not a fan of unnecessary complexity, so I opted for a quick test of cake-autorotate and am amazed by its results. I can watch a stream, do VOIP in TS3 _and_ heavily load the downstream with Steam, with very little effect.

As this is my setup now and it seems to work well, and the development of cake-autorotate continues, I'll probably wait until I test sqm-autorotate.


Thank you so much.

**Comment by Lochnair** [comment]
No problem :-)

I'm not very familiar with ASUS boxes, did it just run out of juice so to speak shaping at those rates?
I'll have a 1000/50 connection soon myself after moving, so there's a decent chance I'll run into the same problem :D

Topton are those Chinese boxes you can get of Amazon/Aliexpress yeah? Been tempted to go that route sometimes, but I won't need it yet.

Heh, in my opinion the biggest additional complexity we have in Lua land is that the Lua Lanes library we depend on, is outdated in OpenWrt, which makes the whole thing a no-go. And yes development has died down here, so if cake-autorate works for you, I'd just stick with that, why mess with it if it works.

I should mention I've been toying with a Rust port of the work in this repository, it's not ready for prime time yet, but it might be something to keep an eye out for. Hopefully it'll end up with one binary/package to install, so it should be much simpler to use.

> Do they work better/worse in specific scenarios?

They might do, but we lacked tooling to really compare the different implementations in a good way.
This is something I might have to bring up in the forum thread, whether we can use the same output format so it's easier to compare results.

**Comment by pannal** [comment]
> I'm not very familiar with ASUS boxes, did it just run out of juice so to speak shaping at those rates?

Yeah pretty much. _none_ of the current "plastic-routers" (also non-ASUS) can effectively shape a GBit using cake. Only with the shenanigans they've implemented (that add their own issues) they're even capable of exceeding the 600MBit mark using fq_codel.

I love the AX capabilities of the ASUS router, but using those very old ARM SoCs (and making a ton of money while doing so), they're basically making their own stuff obsolete by the time it's released.

I've bought a Topton N5105 bare machine for about 180€ and added SODIMM and an SSD. Probably resulted in 260€, which is still massively lower than one of the top-of-the-line plastic routers. That machine now has some old SODIMM stick from an old laptop and a 50€ SSD in it. [Passively cooled and with four (or six) separate 2.5G Intel i226-V NICs.](https://de.aliexpress.com/item/1005004629770173.html?spm=a2g0o.order_list.0.0.606c5c5fJo4PIf&gatewayAdapt=glo2deu) (price fluctuates)

Highly recommended. 6-15W if properly configured in the BIOS (PL1/PL2 limits, speedstep, c-states).

Those units had quality control issues earlier, but the one I got had a proper thermal setup, thermal paste, and even thermal pads on the inductors.

> I should mention I've been toying with a Rust port of the work in this repository, it's not ready for prime time yet, but it might be something to keep an eye out for. Hopefully it'll end up with one binary/package to install, so it should be much simpler to use.

Oooh I'll keep an eye out for that.

Again, thanks!

**Comment by Lochnair** [comment]
> Yeah pretty much. None of the current "plastic-routers" (also non-ASUS) can effectively shape a GBit using cake. Only with the shenanigans they've implemented (that add their own issues) they're even capable of exceeding the 600MBit mark using fq_codel.

Figures. I'll likely end up buying the same box as you or similar. I have a strong dislike for the offloads commonly implemented in those plastic routers.

>I love the AX capabilities of the ASUS router, but using those very old ARM SoCs (and making a ton of money while doing so), they're basically making their own stuff obsolete by the time it's released.

Yeah most of them is good for Wi-Fi only (if that), for wireless I'm thinking of getting Linksys E8450 (also known as Belkin RT3200) or Unifi 6 (LR) (ceiling-mounted). Not too many choices for 802.11ax with OpenWrt support yet.

> I've bought a Topton N5105 bare machine (4 core Celeron, 2.8 GHz boost) for about 180€ and added SODIMM and an SSD...

Well the RAM/SSD combo might be rather overkill, but the box itself looks entirely appropriate :P
I'd probably call it a day with the cheapest RAM/SSD combo they offer.

Thanks for the link!
