### ISSUE TITLE
[FEATURE] Change SQM dependable requirement and Make it look for cake/Modernized Qdiscs~

### ISSUE THREAD

**Issue by GLareFLare22** [sqm-autorate/sqm-autorate#185]
Alot of projects appear to use cake without the need of the SQM app

Is it possible for this script to not look and see if sqm is up, and instead check if cake/fq_codel/modernized qdiscs are in use~

even if it may simplify/complicate the script a bit it'll open up alot more use cases for individuals

**Comment by Lochnair** [comment]
That's probably the right thing to do regardless, as I think right now even if SQM is enabled in the config, if the sqm service is disabled, we won't notice. As mentioned in a todo note for that check, doing `tc qdisc show <intf> ...` might be a better way to check this.

**Comment by GLareFLare22** [comment]
> That's probably the right thing to do regardless, as I think right now even if SQM is enabled in the config, if the sqm service is disabled, we won't notice. As mentioned in a todo note for that check, doing `tc qdisc show <intf> ...` might be a better way to check this.

Removing Lines 179 - 186 in settings.lua
Removing lines 99 -103 in sqm-autorate.lua

appears to allow you to manually assign the interfaces and get it to "work" while using other instances that provide a cake(and other) qdiscs~ that have bandwidth/rate to set "speed"
