### ISSUE TITLE
[ENHANCEMENT] Questions/Tweaks to the setup script...

### ISSUE THREAD

**Issue by richb-hanover** [sqm-autorate/sqm-autorate#36]
**Script Version**
Current `sqm-autorate-setup.sh` script... (see below for output)

**Describe the bug**
Not a bug. Some suggested changes to the text and sequence of the script...

**Priority:** Medium to low - we have a lot of testing of the basic script functionality before thinking about the fussy details of installation process...

* When script detects SQM, change the message to:
`SQM (luci-app-sqm) appears to be installed. Setting up sqm-autorate now...`
* When using `wget` to retrieve files (non-git install), maybe retrieve them after "opkg update" and checking for SQM presence.
* When script detects an existing config file, give its path: e.g., 
`!!! Warning: A config file at /etc/config/sqm-autorate already exists... `
_or maybe_
`>>> Installing config file into /etc/config/sqm-autorate...`
* Is the setup script idempotent? That is, can I run it multiple times, either with the same files, or to update files, and have it continue to work as expected? (I know it'll generate a new `sqm-autorate-NEW` file each time, but I suspect it'd be safe simply to use the earlier config file.)
* What does the script do if SQM is _not_ installed? (I haven't tested)
* What does the script do if SQM is installed but _not enabled_? (I haven't tested)

(Nothing new below here ... I just included the text to refresh my memory of what someone would see...)
```
root@OpenWrt:~/sqm-autorate# git checkout develop/lochnair-mt
Branch 'develop/lochnair-mt' set up to track remote branch 'develop/lochnair-mt' from 'origin'.
Switched to a new branch 'develop/lochnair-mt'
root@OpenWrt:~/sqm-autorate# service sqm-autorate stop
root@OpenWrt:~/sqm-autorate# ./sqm-autorate-setup.sh
> Since this is a Git project, local files will be used and will be COPIED into place instead of MOVED...
>> This is an OpenWrt system.
>>> Refreshing package cache. This may take a few moments...
> Congratulations! You already have SQM (luci-app-sqm) installed. We can proceed with the sqm-autorate setup now...
>>> Installing prerequisite packages via opkg...
Installing https://luarocks.org/vstruct-2.1.1-1.src.rock...
Using https://luarocks.org/vstruct-2.1.1-1.src.rock... switching to 'build' mode
Updating manifest for /usr/lib/luarocks/rocks
vstruct 2.1.1-1 is now built and installed in /usr

>>> Putting config file into place...
!!! Warning: An sqm-autorate config file already exists. This new config file will be created as sqm-autorate-NEW. Please review and merge any updates into your existing sqm-autorate file.
>>> Putting sqm-autorate Lua file into place...
>>> Putting service file into place...
> All done! You can enable and start the service by executing 'service sqm-autorate enable && service sqm-autorate start'.
```

**Comment by chas-iot** [comment]
**Is the setup script idempotent? That is, can I run it multiple times, either with the same files, or to update files, and have it continue to work as expected?**
From my testing, the answer is yes to this point.

**Comment by Fail-Safe** [comment]
@chas-iot Yes sir, it is idempotent as it currently is written. The intent was to have it be such so it was very easy to have a "one-click" way to stay up to date, or just reset one's environment if something gets screwed up.

The exception to this, and this can be discussed further, is the script will **not** overwrite an existing sqm-autorate config file in /etc/config/. I debated on how to handle that and landed on the way opkg handles duplicate configs. It creates the new config file with a suffix (I believe) and then tells you to look at the new file to compare changes.
