### ISSUE TITLE
[BUG] "lua sqm-autorate.lua version" option gives stack trace

### ISSUE THREAD

**Issue by richb-hanover** [sqm-autorate/sqm-autorate#47]
**Script Version**
0.0.1b5 version of the testing/lua-threads branch

**Describe the bug**
`lua /usr/lib/sqm-autorate/sqm-autorate.lua version` gives a stack trace (below)

**Expected behavior**
Display version string

If I add LUA_PATH and LUA_CPATH environment variables it works.

**OpenWrt Details (please paste your output from `cat /etc/os-release`):**
 - OS-Release: 21.02.1
 - Connection Type + Speed: 25/25 symmetric fiber

```
root@D-Link-DIR-878:~# lua /usr/lib/sqm-autorate/sqm-autorate.lua version
lua: module 'vstruct' not found:
	no field package.preload['vstruct']
	no file './vstruct.lua'
	no file '/usr/share/lua/vstruct.lua'
	no file '/usr/share/lua/vstruct/init.lua'
	no file '/usr/lib/lua/vstruct.lua'
	no file '/usr/lib/lua/vstruct/init.lua'
	no file './vstruct.so'
	no file '/usr/lib/lua/vstruct.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: ?
	[C]: in function 'require'
	/usr/lib/sqm-autorate/sqm-autorate.lua:41: in main chunk
	[C]: ?
```

**Comment by Lochnair** [comment]
Right, really need to get a package for vstruct done. Will have a look at that ASAP

**Comment by richb-hanover** [comment]
> Right, really need to get a package for vstruct done. Will have a look at that ASAP

Since the setup.sh script works fine as-is, we might not need a vstruct package. 

Naive question about Lua - would it be possible to display the version number without attempting to load in the vstruct module?

**Comment by Lochnair** [comment]
> Since the setup.sh script works fine as-is, we might not need a vstruct package.
Just my personal preference having packages for the libraries we need to be fair, but no we don't _need_ it
We might be able to use a luarocks option to install vstruct in the place OpenWrt looks for it, so you can run the script without copying the LUA_PATH environment variables.

> Naive question about Lua - would it be possible to for the script to display its version number without attempting to load in the vstruct module?
That is actually solved in the `refactor-to-modules` branch I believe. Most modules are now loaded inside the `conductor()` function, which is called after the argument check runs.

Lua is pretty lenient, so you could do the same in the current main branch as well with some light refactoring

**Comment by richb-hanover** [comment]
I'm going to close this for now. We no longer recommend manual testing, so it'll be relatively rare that someone bumps into it.
