### ISSUE TITLE
logrotate files in tmp

### ISSUE THREAD

**Issue by dim-geo** [sqm-autorate/sqm-autorate#48]
sqm-autorate service is using it's own log which is not rotated.
That can cause an issue and fill RAM.
Consider using syslog that is automatically rotated by the system.

https://github.com/Fail-Safe/sqm-autorate/blob/6a1f66cece3c4fc2bcd5e29ffdd96b99067a513b/service/sqm-autorate.service#L13

**Comment by chas-iot** [comment]
Should log-rotate should also apply to the stats files?

Should log-rotate also incorporate log deletion? Say an option to keep only the current and previous, only the current, or keep all?
